const images = {
  Logo: require('../../assets/Icons/Logo.png'),
  getStarted: require('../../assets/Icons/getStarted.png'),
  Google: require('../../assets/Icons/Google.png'),
  Facebook: require('../../assets/Icons/Facebook.png'),
  loginFrame: require('../../assets/Icons/loginFrame.png'),
  mail: require('../../assets/Icons/mail.png'),
  lock: require('../../assets/Icons/lock.png'),
  notification: require('../../assets/Icons/notification.png'),
  menu: require('../../assets/Icons/menu.png'),
  search: require('../../assets/Icons/search.png'),
  HeaderImage: require('../../assets/Icons/HeaderImage.png'),
  playIcon: require('../../assets/Icons/playIcon.png'),
  Mask: require('../../assets/Icons/Mask.png'),
  Mask_1: require('../../assets/Icons/Mask_1.png'),
  lockPremium: require('../../assets/Icons/lockPremium.png'),
  premium_quality: require('../../assets/Icons/premium_quality.png'),
  premiumThumbnail: require('../../assets/Icons/premiumThumbnail.png'),
  Avatar: require('../../assets/Icons/Avatar.png'),
  setting: require('../../assets/Icons/setting.png'),
  subscribe: require('../../assets/Icons/subscribe.png'),
  drawerNotification: require('../../assets/Icons/drawerNotification.png'),
  favouriteDrawer: require('../../assets/Icons/favouriteDrawer.png'),
  help: require('../../assets/Icons/help.png'),
  back: require('../../assets/Icons/back.png'),
  heart: require('../../assets/Icons/heart.png'),
  share: require('../../assets/Icons/share.png'),
  splash: require('../../assets/Icons/splash.png'),
  // Payment Icons
  upi: require('../../assets/Icons/paymentIcons/upi.png'),
  papal: require('../../assets/Icons/paymentIcons/papal.png'),
  net: require('../../assets/Icons/paymentIcons/net.png'),
  card: require('../../assets/Icons/paymentIcons/card.png'),
  credit_card: require('../../assets/Icons/paymentIcons/credit_card.png'),
  master: require('../../assets/Icons/paymentIcons/master.png'),
  information: require('../../assets/Icons/paymentIcons/information.png'),

  // setting Icons
  settingPayments: require('../../assets/Icons/Settings/settingPayments.png'),
  settingSheild: require('../../assets/Icons/Settings/settingSheild.png'),
  settingTerm: require('../../assets/Icons/Settings/settingTerm.png'),
  settingUser: require('../../assets/Icons/Settings/settingUser.png'),
  editIcon: require('../../assets/Icons/Settings/editIcon.png'),
  dropDown: require('../../assets/Icons/Settings/dropDown.png'),
  mainViewNotification: require('../../assets/Icons/Settings/mainViewNotification.png'),
  favouriteMAin: require('../../assets/Icons/Settings/favouriteMAin.png'),
  closeIcon: require('../../assets/Icons/Settings/close.png'),

  messageEdit: require('../../assets/Icons/Settings/messageEdit.png'),
  phone_call: require('../../assets/Icons/Settings/phone_call.png'),

};
export default images;